server:
  port: 3344


spring:
  application:
    name: cloud-config-center #注册金Eureka服务器的微服务名称
  cloud:
    config:
      server:
        git:
          uri: https://github.com/tmy110/sprincloud-config.git #GitHub上面的git仓库名称
          #搜索目录
          search-paths:
            - spring-config
            #读取分支
      label: master
#rabbitmq相关配置
rabbitmq:
  host: localhost
  port: 5672
  username: guest
  password: guest

#服务注册到eureka地址
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka

#rabbitmq相关配置，暴露bus刷新配置的端点
management:
  endpoints:
    web:
      exposure:
        include: "bus-refresh"

